import Config

steady_dev_server? =
  System.get_env("SHEAF_PHOENIX_DEV_MODE") in ~w(steady plain stable no_reload no-reload)

watchers =
  if steady_dev_server? do
    []
  else
    [
      esbuild:
        {Esbuild, :install_and_run, [:sheaf, ~w(--sourcemap=inline --watch)]},
      tailwind: {Tailwind, :install_and_run, [:sheaf, ~w(--watch)]}
    ]
  end

live_reload =
  if true or steady_dev_server? do
    []
  else
    [
      web_console_logger: true,
      patterns: [
        # Static assets, except user uploads
        ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
        # Gettext translations
        ~r"priv/gettext/.*\.po$"E,
        # Router, Controllers, LiveViews and LiveComponents
        ~r"lib/sheaf_web/router\.ex$"E,
        ~r"lib/sheaf_web/(controllers|live|components)/.*\.(ex|heex)$"E
      ]
    ]
  end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sheaf, SheafWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: not steady_dev_server?,
  reloadable_apps: [:sheaf],
  # debug_errors: not steady_dev_server?,
  secret_key_base:
    "EZd+P1fNcVZFqt1rjqJ8sm+U6xvhE09n6hcPmky7kWWAUq9KLR9Crh8GXd8lwwnC",
  watchers: watchers

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :sheaf, SheafWeb.Endpoint, live_reload: live_reload

# Enable dev routes for dashboard and mailbox
config :sheaf, dev_routes: false

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix,
       :plug_init_mode,
       if(steady_dev_server?, do: :compile, else: :runtime)

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  # not steady_dev_server?,
  debug_heex_annotations: true,
  # not steady_dev_server?,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  # not steady_dev_server?
  enable_expensive_runtime_checks: false
